/** Base de datos de usuarios DEMO — Mercado Garmendia (window.MG_USERS) */
window.MG_USERS = (function () {
  "use strict";
  const P = (n) => String(n).padStart(3, "0");
  function mkToken(n) {
    const chars = "0123456789abcdef";
    let x = (n * 2654435761 + 1013904223) >>> 0;
    let s = "";
    for (let i = 0; i < 27; i++) {
      x ^= x << 13; x >>>= 0;
      x ^= x >>> 17; x >>>= 0;
      x ^= x << 5; x >>>= 0;
      s += chars[x % 16];
    }
    return "mg" + P(n) + s;
  }
  const KW = [
    "toro",
    "chuy",
    "feliz",
    "nortenos",
    "sinaloa",
    "martin",
    "rincon",
    "trigal",
    "espiga",
    "pepe",
    "pan",
    "michoacana",
    "jose",
    "esperanza",
    "vaquita",
    "rancho",
    "lupita",
    "polo",
    "flor",
    "lazaro",
    "azul",
    "barcos",
    "camaron",
    "rosa",
    "pacifico",
    "isla",
    "cuco",
    "tierra",
    "gallo",
    "lupe",
    "pollos",
    "granja",
    "corral",
    "huerto",
    "cosecha",
    "beto",
    "campo",
    "tropical",
    "valle",
    "isidro",
    "huerta",
    "central",
    "surtidor",
    "mari",
    "rincon",
    "esquina",
    "miguel",
    "ahorro",
    "providencia",
    "lalo",
    "nixtamal",
    "masa",
    "nacho",
    "molcajete",
    "sinaloense",
    "carmen",
    "sabor",
    "abuela",
    "sinaloense",
    "pera",
    "tradicionales",
    "fonda",
    "guiso",
    "juan",
    "naranjal",
    "vita",
    "naturista",
    "fruta",
    "condimento",
    "ramirez",
    "india",
    "guero",
    "gallo",
    "cuco",
    "granjita",
    "guero",
    "refugio",
    "felix",
    "hacienda",
    "granero",
    "portillo",
    "serapio",
    "palapa",
    "oasis",
    "luz",
    "descanso",
    "grano",
    "taza",
    "irma",
    "dulzura",
    "cuca",
    "rosas",
    "beto",
    "primavera",
    "remedio",
    "ana",
    "salud",
    "estilo",
    "rocha",
    "celia",
    "arte",
    "jimenez",
    "patricio",
    "moda",
    "paso",
    "ruben",
    "comodidad",
    "torres",
    "clavo",
    "felipe",
    "tornillo",
    "rey",
    "lopez",
    "elvira",
    "carnaval",
    "lunas",
    "mario",
    "paraiso",
    "galaviz",
    "golosa",
    "antojo",
    "sabores",
    "limpio",
    "ruiz",
    "sosa",
    "sol",
    "aguja",
    "medina",
    "dedal",
    "brillante",
    "carmen",
    "plata",
    "tesoro",
    "lapiz",
    "guerrero",
    "raul",
    "circuito",
    "fix",
    "chip",
    "plus",
    "feliz",
    "lopez",
    "ilusion",
    "arte",
    "fogon",
    "raices",
    "palma",
    "relojero",
    "costurera",
    "llaves",
    "azul",
    "isla",
    "espiga",
    "flor",
    "mama",
    "pasillo",
    "alegrias",
    "c",
    "puerto",
    "cosecha",
    "corral",
    "olla",
    "culiacan",
    "esperanza",
    "nortenos",
    "gallo",
    "vaquita",
    "pacifico",
    "tierra",
    "martin",
    "trigal",
    "valle",
    "feliz",
    "licua2go",
    "chela",
    "natas",
    "primo",
    "dulce",
    "sinaloenses",
    "chuy",
    "rincon",
    "lupe",
    "pan",
    "rosa",
    "cuco",
    "pepe",
    "lazaro",
    "lupita",
    "abuela",
    "juguete",
    "guero",
    "guirola",
    "frescas",
    "bahia",
    "norte",
    "toro",
    "jose",
    "sinaloa",
    "michoacana",
    "azul",
    "isla",
    "espiga",
    "flor",
    "mama",
    "pasillo",
    "alegrias",
    "c",
    "puerto",
    "cosecha",
    "corral",
    "olla",
    "culiacan",
    "esperanza",
    "nortenos",
    "gallo",
    "vaquita",
    "pacifico",
    "tierra",
    "martin",
    "trigal",
    "valle",
    "feliz",
    "licua2go",
    "chela",
    "natas",
    "primo",
    "dulce",
    "sinaloenses",
    "chuy",
    "rincon",
    "lupe",
    "pan",
    "rosa",
    "cuco",
    "pepe",
    "lazaro",
    "lupita",
    "abuela",
    "juguete",
    "guero",
    "guirola",
    "frescas",
    "bahia",
    "norte",
    "local",
    "local",
    "sinaloa",
    "michoacana",
    "azul",
    "isla"
  ];
  const mk = (n) => ({ idLocal: n, username: "local" + P(n), password: "Mg2026*" + P(n), keyword: KW[n - 1] + P(n), qrToken: mkToken(n) });

  const users = [];
  users.push({ idLocal: 1, username: "local001", password: "Mg2026*001", keyword: "toro001", qrToken: "mg0012b9de2200a75022f5911fef1a64" });
  users.push({ idLocal: 2, username: "local002", password: "Mg2026*002", keyword: "chuy002", qrToken: "mg00231413a9e2328e33c975d82cd046" });
  users.push({ idLocal: 3, username: "local003", password: "Mg2026*003", keyword: "feliz003", qrToken: "mg003f47ff030934ecbb0dd892036dcc" });
  users.push({ idLocal: 4, username: "local004", password: "Mg2026*004", keyword: "nortenos004", qrToken: "mg00475c1b7ce779914fc531617c9b30" });
  users.push({ idLocal: 5, username: "local005", password: "Mg2026*005", keyword: "sinaloa005", qrToken: "mg005bb7e7bd3582de70c1a2732631c5" });
  // Locales intermedios 6..245 generados en bucle
  for (let n = 6; n <= 245; n++) users.push(mk(n));
  users.push({ idLocal: 246, username: "local246", password: "Mg2026*246", keyword: "local246", qrToken: "mg246c74f74b8815d0ab7ec2aedc7e8f" });
  users.push({ idLocal: 247, username: "local247", password: "Mg2026*247", keyword: "sinaloa247", qrToken: "mg247e1a93c7c54fe49f2077923dce2c" });
  users.push({ idLocal: 248, username: "local248", password: "Mg2026*248", keyword: "michoacana248", qrToken: "mg248c63f1f460e1b9827f7d85bb970e" });
  users.push({ idLocal: 249, username: "local249", password: "Mg2026*249", keyword: "azul249", qrToken: "mg24927b33a2658bc839f60028bd0b76" });
  users.push({ idLocal: 250, username: "local250", password: "Mg2026*250", keyword: "isla250", qrToken: "mg2507202e32325f6b9227a1bc0d3b2a" });
  return users;
})();
